// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMEGw71T-RxFLtEbgEQ0iqhXiaHXa6HY0',
    appId: '1:932043130642:web:e85183f93e41b65ee955cb',
    messagingSenderId: '932043130642',
    projectId: 'ao-gosto-app-c0b31',
    authDomain: 'ao-gosto-app-c0b31.firebaseapp.com',
    storageBucket: 'ao-gosto-app-c0b31.firebasestorage.app',
    measurementId: 'G-VKQBFM2WER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkXcfafUxaCIyqgminaGO4ZvPpPcIB7fw',
    appId: '1:932043130642:android:b1c7706e4a4c8363e955cb',
    messagingSenderId: '932043130642',
    projectId: 'ao-gosto-app-c0b31',
    storageBucket: 'ao-gosto-app-c0b31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaRtV042woLZ3WeycVlL3ORsLWTkzi5S8',
    appId: '1:932043130642:ios:c589a00afdfb7ba2e955cb',
    messagingSenderId: '932043130642',
    projectId: 'ao-gosto-app-c0b31',
    storageBucket: 'ao-gosto-app-c0b31.firebasestorage.app',
    iosBundleId: 'com.example.entregador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaRtV042woLZ3WeycVlL3ORsLWTkzi5S8',
    appId: '1:932043130642:ios:c589a00afdfb7ba2e955cb',
    messagingSenderId: '932043130642',
    projectId: 'ao-gosto-app-c0b31',
    storageBucket: 'ao-gosto-app-c0b31.firebasestorage.app',
    iosBundleId: 'com.example.entregador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMEGw71T-RxFLtEbgEQ0iqhXiaHXa6HY0',
    appId: '1:932043130642:web:e37421731c01f521e955cb',
    messagingSenderId: '932043130642',
    projectId: 'ao-gosto-app-c0b31',
    authDomain: 'ao-gosto-app-c0b31.firebaseapp.com',
    storageBucket: 'ao-gosto-app-c0b31.firebasestorage.app',
    measurementId: 'G-M6CJ0WQPQP',
  );
}
